### ISSUE TITLE
Add informative error message when package contains no function.

### ISSUE THREAD

**Issue by maurolepore** [ropenscilabs/pkginspector#1]
Data-packages contain no functions. Running `rev_dependency_usage()` on packages with no functions result in error with uninformative message:

``` r
 Error in `[.data.frame`(`*tmp*`, , 2) : undefined columns selected 
```
I suggest checking for this issue and throwing informative error message or returning empty dataframe with warning.

**Comment by OmaymaS** [comment]
I tried this with a new empty package, and I get informative errors thrown by `check_pkg_dir()` which is called by `map_r_package()`.

For instance:

- If there's no R folder:
`Error in check_pkg_dir(path) : No R folder, is this an R package?`

- If there's an empty R folder
```
> rev_dependency_usage("E:/testpkg")
 E:/testpkg/R is empty, no R source files
```

So what could be different on your side?
