### ISSUE TITLE
Help file statistics

### ISSUE THREAD

**Issue by noamross** [ropenscilabs/pkginspector#14]
It's very hard to make standardized tests for what to include in documentation, because things vary quite a bit.  Nonetheless, there are a lot of things I'd like to know about the help files of a package I'm looking at, such as

-  Do help files have `@return` fields?  This is supposed to be a requirement for anything that returns an object, but it can't really be tested because there are lots of functions that don't return objects and that's a very difficult thing to parse. 
- Are lots of functions aggregated together in one help file?  At times this is OK, but a lot of times its a flag for overly confusing help files with many many arguments.

One idea would be to generate a table of help files, their length, whether they contain certain fields (examples, return value), and how many/which functions they contain.

**Comment by jtr13** [comment]
I like this idea. Let's discuss at some point -- if I'm pointed in the right direction I think I could flesh this out.
