### ISSUE TITLE
Unifying the usage of functions, return classes, etc.

### ISSUE THREAD

**Issue by OmaymaS** [ropenscilabs/pkginspector#16]
Since there are different ways returning a dataframe, or iterating over a list, should we unify this?

For instance:
- should we pick either the `apply` or `map` family, and use it in all our functions?
- should we agree whether to return `data.frame`, `dplyr::data_frame` , `tibble`, etc.?
- Other ?

**Comment by boshek** [comment]
I'm inclined to with go with *apply stuff and data.frame so that the package itself appears to be agnostic on those matters.

**Comment by OmaymaS** [comment]
Although I use `map` a lot, but I see the point of using `apply` family. We can get feedback from the rest and decide.

**Comment by boshek** [comment]
I LOVE `map`! Don't get me wrong. Just feels like a better analysis tool rather than a programming one.

**Comment by OmaymaS** [comment]
Sure, I have no preference when it comes to packages. I personally had the same thoughts before while writing a package, wondering if I should use `apply` because it is more common and doesn't require importing `purrr`. So it is fine to go for `apply` if it serves all the needs here.
