### ISSUE TITLE
Maybe ideas that aren't here yet

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/pkginspector#18]
Just copying stuff over from https://github.com/ropensci/onboarding-meta/issues/18 since this repo is the home for such ideas. 😺 

Initially from https://github.com/ropensci/onboarding/issues/125

- package has code of conduct
- exported functions are consistent in snake/camel naming convention 
- preferred packages are used
- the global environment is not directly manipulated
- package has CI and badges
- package uses appveyor is compiled code is included 
- common name conflicts are avoided
- If README has code, README.Rmd is used
- Package has a vignette 
- Package has top level documentation 
- CI doesn't skip tests
* could use available to check pkg name
* check if using roxygen style docs
* package has at least some tests
* check that all exported fxns have a `@examples` roxygen tag with at least 1 line of code (i.e., 1 example)
* might want to flag when people use `Depends` in `DESCRIPTION` to make sure it's really needed
* test of the package with different loading methods (see [this comment](https://github.com/ropensci/onboardi

**Comment by jtr13** [comment]
@maelle Just checking that these ideas are in the right place... this is the unconf18 spinoff of pkgviewr, which remains the main package for rOpenSci package reviews

**Comment by maelle** [comment]
I think so? but not sure what @annakrystalli thinks about the scope of both packages.

I thought `pkginspector` was something authors and editors could use too, what's fuzzier in my head is the difference with `goodpractice` actually. I might need a flow chart or some sort of diagram 😃

**Comment by noamross** [comment]
Here is how I think of the scope and relationship f these tools:
-  **pkgreviewer** provides a workflow and template for doing reviews
- **pkginspector** provides functions to report on and visualize package structure, functions, metrics, so as to  better understand and evaluate a package
- _something_  contains additional tests that enforce binary standards like the ones listed above, as plugins for **goodpractice**.  I have thought that this would be in **rodev** or something similar, but it's possible it could put into **pkginspector**
- **launchboat** runs a series of test and diagnostics, including **devtools**/**testthat** tests, **goodpractice** along with RO-specific plugins, and many **pkginspector**, and assembles them into a report.

**Comment by maelle** [comment]
Interesting, thanks!

I think of `rodev` as something very simple now, mostly templating based on `usethis`, but I'm open to discussion.

`pkgreviewr` would potentially launch (hehe) a `launchboat` function then?
