### ISSUE TITLE
Hex Sticker

### ISSUE THREAD

**Issue by OmaymaS** [ropenscilabs/pkginspector#20]
I thought about sth rough for a hex sticker as follows:

![pkg_hex2](https://user-images.githubusercontent.com/13340411/42477571-e1002406-83d1-11e8-9b92-94e5c49897ac.png)

I tried [hexSticker](https://github.com/GuangchuangYu/hexSticker) package to overlay an image on a hex sticket template, but I haven't reached a good form yet. 

Any suggestions for other quick ways?

**Comment by jtr13** [comment]
I'm clueless but I'll ask around. What specifically is the issue with hexSticker?

**Comment by OmaymaS** [comment]
It just doesn't scale things as I want. I migh go to photoshop for quicker design.

**Comment by OmaymaS** [comment]
Picked a sticker
<img src = "https://user-images.githubusercontent.com/13340411/42736345-9e54641c-8865-11e8-8e7b-b3ce85d244dc.png" width = "25%">
