### ISSUE TITLE
S4 methods

### ISSUE THREAD

**Issue by llrs** [ropenscilabs/pkginspector#23]
I have installed the package to test it, and I am wonder what is the stance of the package regarding S4 methods.

I tried in a new package I'm developing and they seem to be considered as not exported or not at all despite being on the NAMESPACE of the package:
![pkginspector_gseadv](https://user-images.githubusercontent.com/6818218/42835303-c513439a-89f8-11e8-8d60-7e910fd449e5.png)
In the picture it doesn't appear the methods such as `modify` that are implemented in the package (see [llrs/GSEAdv](https://github.com/llrs/GSEAdv))
I compared with `mvbutils::foodweb(where = "package:GSEAdv")`
![foodweb_gseadv](https://user-images.githubusercontent.com/6818218/42835944-4bf8bbd2-89fa-11e8-9e02-f4e9f506ccee.png)

And here it appears as a without links to internal functions (see on the right of the first line without lines above those terms with lines)
Thanks

**Comment by jtr13** [comment]
Thanks for testing out the package; the feedback is very helpful. We will look into why these particular functions are missing. We rely on `functionMap::map_r_package` to find functions and we know that it has some flaws that we intend to fix. I had trouble getting `mvbutils::foodweb` to work at all but now that I see that it does I will give it another go.
