### ISSUE TITLE
Passing installed package names Vs. package source path

### ISSUE THREAD

**Issue by OmaymaS** [ropenscilabs/pkginspector#4]
I was reviewing the functions and felt that it might be confusing that we ask the user to pass the package source path then things will fail if the package is not installed which is in another directory. Although some functions might not need the path of the package source.

For instance:

- [`rev_signature()`](https://github.com/ropenscilabs/pkginspector/blob/5b7587625eafa27aa8b71b9cf9c857cb4f2b3420/R/rev.R#L77) could just take the name of the installed package since it does not call `functionMap::map_r_package` which requires the source path.

*This is a modified version of rev_signature()*
```
rev_signature2 <- function(package = "viridisLite"){
  check_if_installed(package)

  f_name <- unclass(utils::lsf.str(envir = asNamespace(package), all = TRUE))
  f_bare_args <- unlist(lapply(f_name, get_string_arguments, package = package))
  
  f_args <- paste0(f_name, " ", gsub("function ", "", f_bare_args))
  data.frame(f_name, f_args)
}
```
`> rev_signature2("viridisLite")`

- On the other hand functions like `rev_signature()`, `rev_calls()`, `rev_args()` call  `functionMap::map_r_package`, so they need the source path.

So  do you think sticking to the local path in all the functions even if they don't need it is the best option here?

**Comment by boshek** [comment]
This seems reasonable to me. But just for clarity, you are proposing to modify `rev_signature` rather than create `rev_signature2` right?

**Comment by OmaymaS** [comment]
yes, exactly. I propose to modify `rev_signature`.  I created a pull request with the modifications.
