### ISSUE TITLE
fix rev_fn_summary warnings

### ISSUE THREAD

**Issue by jtr13** [ropenscilabs/pkginspector#8]
```
Warning messages:
1: In vattrs[[name]][index] <- value :
  number of items to replace is not a multiple of replacement length
2: In `[<-.factor`(`*tmp*`, thisvar, value = 0) :
  invalid factor level, NA generated
```
I think the length issue is related to removing duplicates.

**Comment by jtr13** [comment]
I got the warnings with `skimr`.  I'll look into what's happing with `rev_fn_summary()` -- I just tested it and I'm getting the warnings only from `rev_fn_summary()`, not `rev_signature()`.  `rev_fn_summary()` seems to be adding an extra (weird) first row that's causing the problem.  (For example, with `skimr`, `align_decimal` is the first row of the dataframe returned by `rev_signature()` but the second row of `rev_fn_summary()`, while the first row is NA.

**Comment by jtr13** [comment]
The first warning is coming from `create_package_igraph()`

**Comment by OmaymaS** [comment]
Ah I think it is coming from [set_vertex_attr() call](https://github.com/ropenscilabs/pkginspector/blob/07eda134007ccec9d30285383120a1e7a44b16a1/R/utils.R#L25)

I created a pull request with the edit. I think we we should use `unique_nodes` instead of `node_df`

**Comment by jtr13** [comment]
Fixed with https://github.com/ropenscilabs/pkginspector/pull/10
