### ISSUE TITLE
problem with vis_package()

### ISSUE THREAD

**Issue by jtr13** [ropenscilabs/pkginspector#9]
In skimr example, when `skim_render()` is clicked, `is_windows` and `fix_unicode` are labelled even though they are not dependents (icons are rendered correctly)

**Comment by OmaymaS** [comment]
I tried it and that's what I get.
![nw](https://user-images.githubusercontent.com/13340411/40995925-cefd4fae-6900-11e8-8e91-a824aca94b37.png)

**Comment by jtr13** [comment]
Hmm, you don't have the labeling problem but you're missing the icons.  I added `%>% addFontAwesome()` which hopefully will fix that.
